mglaman/phpstan-drupal

src/DependencyInjection/DrupalExtension.php, src/Drupal/Bootstrap.php, src/Drupal/Extension.php, src/Drupal/ExtensionDiscovery.php, src/Drupal/ServiceMap.php, src/Rules/Classes/EnhancedRequireParentConstructCallRule.php, src/Rules/Drupal/GlobalDrupalDependencyInjectionRule.php, src/Rules/Drupal/PluginManager/PluginManagerSetsCacheBackendRule.php
This tightens up some of the types used in the project, ensuring things are never set to values they cannot be, and adding closure params/return types. It also avoids calling methods that give the same result more than once.
=> Improve type coverage

README.md
Hola!
Testing this package, and just noticed what I find is a somewhat bad advice :)
One probably wants to install the deprecation rules package as a dev dependency (as one does with all other phpstan libraries)
=> Suggest installing deprecation rules as dev dependency

tests/DrupalIntegrationTest.php
Fixes #51 by identifying the specific offending file.
=> Specifically check for ContainerNotInitializedException

src/DependencyInjection/DrupalExtension.php
I'm not sure why the dirname was cut by 2 levels, but this make trouble with DrupalTestBot.
See https://www.drupal.org/project/upgrade_status/issues/3050653
It seems what DrupalTestBot does is something along the line
```
git clone drupal
composer install
install upgrade_status
```
In this case the autoload.php is in the root dir:
```
core
vendor
autoload.php
```
all in the same directory.
while when I use composer create project the drupal root is in a sub directory and the vendor one level above and then the current code works.
=> Fixes Drupal core can't be find by DrupalTestBot

.circleci/config.yml, src/Drupal/Bootstrap.php, tests/fixtures/config/circleci-phpunit.xml
Using phpstan 0.11.3 and dev of phpstan-drupal (after #75 ) and the drupal upgrade_status module dev version you receive an error "Drupal already defined"
Issue for this is that `require` and not `require_once` is used.
I already mentioned this in https://github.com/mglaman/phpstan-drupal/pull/71#issuecomment-501213378
After talking with Gábor Hojtsy, we decided its maybe better to create a separate PR for this instead of only in this comment.
As you already mentioned in https://github.com/mglaman/phpstan-drupal/pull/71#issuecomment-501253478 its a good question if this `require` is needed at all, as composer should load it anyways.
Maybe get this in now and do the refactoring/removing in #71 ?
In this way we should get the drupal tests running and then can test the refactoring better?
=> Prevent files from being required twice

.circleci/config.yml, src/Drupal/Bootstrap.php, tests/fixtures/config/circleci-phpunit.xml
This tests part of the failures/errors discussed in https://github.com/mglaman/phpstan-drupal/pull/77
```
'Drupal' => $baseDir . '/tests/fixtures/drupal/core/lib/Drupal.php',
```
=> \Drupal static class included in classmap

src/Drupal/Bootstrap.php
This is a follow for https://github.com/mglaman/phpstan-drupal/pull/88. It loads the build tests that are provided by a module or a theme.
=> Include new 8.8.x test namespaces for modules

src/DependencyInjection/DrupalExtension.php
This fixes #31 
So, I do not know how the piece of code is supposed to actually work, since it used to just set service providers in an array and never use them for anything. 
The point is, it would even work had the autoloader already mapped the service providers, because then they would be registered by class_exists. But since this runs before the registering of classes in Bootstrap::addModuleNamespaces service providers are never found.
I have now solved this by assigning all potential module service provider to the drupalServiceMap parameter. I am pretty sure this could be factored out to its own factory, and actually check when things are needed, but this solves the problem and should not give any side effects.
The most annoying part of the bug is that class definitions are cached, …
=> Make sure the service providers can be found with cold caches

.circleci/config.yml
Disable the job for now until we can try to provide integration testing with it.
=> The Upgrade Status pipeline timesout on Circle CI

extension.neon, src/Drupal/DrupalAutoloader.php, tests/fixtures/config/drupal-phpstan.neon, tests/fixtures/config/phpunit-drupal-phpstan.neon, tests/src/BootstrapTest.php
This defaults the drupal.drupal_root container parameter to the current working directory variable, and marks it as a required value in the schema.
Fixes #104
=> Default drupal_root to current working directory

src/Drupal/DrupalAutoloader.php, tests/fixtures/drupal/modules/module_with_tests/module_with_tests.info.yml, tests/fixtures/drupal/modules/module_with_tests/tests/src/TestSite/ModuleWithTestsTestSite.php, tests/fixtures/drupal/modules/module_with_tests/tests/src/Traits/ModuleWithTestsTrait.php, tests/fixtures/drupal/modules/module_with_tests/tests/src/Unit/ModuleWithTestsTest.php, tests/src/DrupalIntegrationTest.php
See [drupal-check #124](https://github.com/mglaman/drupal-check/issues/124).
The autoloader infers that the behavior should match [drupal_phpunit_get_extension_namespaces](https://api.drupal.org/api/drupal/core%21tests%21bootstrap.php/function/drupal_phpunit_get_extension_namespaces/8.9.x), but the logic behind this does not match that function.
This removes the hard-coded namespaces and only adds the two necessary namespaces for extensions:
1. `\Drupal\module_name` -> module_root/src
2. `\Drupal\Tests\module_name` -> module_root/tests/src
I wasn't sure about tests so I added a module that implement a couple of test namespaces, but I didn't add all the current possibilities.
=> Fixes extension autoloader to behave like Drupal core

src/Type/ServiceDynamicReturnTypeExtension.php, tests/fixtures/drupal/modules/phpstan_fixtures/phpstan_fixtures.module, tests/fixtures/drupal/modules/phpstan_fixtures/src/AppRootParameter.php, tests/src/DrupalIntegrationTest.php
First of all, thanks for this great project, I started toying around with it recently and am liking it a lot. :+1: 
I found a quibble, though, which is what this PR is for:
I could not find a way with the current inspection to do something like:
```php
$app_root = $this->container->get('app.root');
$some_path = $app_root . '/core/includes/install.inc';
```
That would result in:
> Binary operation "." between SplString and '/core/incl…' results in an error.
Casting `$app_root` to a string is also not allowed, so I was pretty much out of options as far as I could tell.
This seemed to be a sensible way to fix it, but I'm certainly open to other suggestions.
=> Fix type inspection for app.root service

src/Rules/Deprecations/AccessDeprecatedConstant.php
Per @Berdir in https://www.drupal.org/project/drupal/issues/2902895#comment-13461286,
> @catch and @alexpott agreed in Slack to postpone removing the constant to D10 as it seems like a lot of work is left that close to the first beta deadline. We can keep working on its removal in core but should also do an issue to change the deprecation message. And I guess remove it again from the hardcoded list in phpstan-drupal?
See https://www.drupal.org/node/3113284 for the issue w/ the patch
=> See https://www.drupal.org/node/3113284.

README.md
I created a new PHPStan website with full-fledged documentation, so I'd like all links to reflect this :) Thanks.
=> Update README with link to the PHPStan website

src/Rules/Drupal/PluginManager/PluginManagerSetsCacheBackendRule.php, tests/src/DrupalIntegrationTest.php
=> plugin managers are not required to specify cache tags

extension.neon, src/Drupal/ExtensionDiscovery.php, src/Rules/Drupal/LoadIncludes.php, tests/fixtures/drupal/modules/phpstan_fixtures/phpstan_fixtures.module, tests/src/DrupalIntegrationTest.php
I went a different direction with fixing #124. Since it is the actual static analisis that will need to uncover the calls to loadInclude from the module handler service, I made this a rule instead. This way we can actually uncover when calls are being made but the files do not exist.
A bonus is that we actually get the files included, and functions that are not recognized will now be recognized
=> Add a rule for loadIncludes. Fix #124

composer.json, src/Drupal/DrupalAutoloader.php, tests/src/DrupalIntegrationTest.php
=> Fix autoloading of PhpunitCompatibilityTrait

src/Rules/Drupal/GlobalDrupalDependencyInjectionRule.php
=> Allow \Drupal calls in traits and tests

.circleci/config.yml
The implementation is based on [the CircleCI documentation](https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow).
This closes #146.
=> Run CircleCI tests on a weekly schedule

.circleci/config.yml, .travis.yml, phpunit.xml
Instead of getting coverage to run in the CI, just disable it. Coverage can be a local thing.
Fixes #155
=> Disable xdebug coverage in CI

src/Rules/Drupal/GlobalDrupalDependencyInjectionRule.php
I recently started getting errors when running phpstan on my drupal code:
> Internal error: Internal error: PHPUnit\Framework\TestCase is not an interface in file <filename.php>
> Run PHPStan with --debug option and post the stack trace to: https://github.com/phpstan/phpstan/issues/new?template=Bug_report.md
This traced down to \PHPStan\Rules\Drupal\GlobalDrupalDependencyInjectionRule:48 where a list of interface names are checked. Though, the first item of this list is an abstract class and not an interface.
=> Use PHPUnit\Framework\Test interface instead of TestCase class

src/Drupal/DrupalAutoloader.php
fix : 
```
TypeError thrown in /project/vendor/mglaman/phpstan-drupal/src/Drupal/DrupalAutoloader.php on line 183 while loading bootstrap file /project/vendor/mglaman/phpstan-drupal/drupal-autoloader.php: str_replace(): Argument #3 ($subject) must be of type array|string, bool given
```
#150
=> fix TypeError in DrupalAutoloader

.github/workflows/php.yml, .gitignore, composer.json, drupal-phpunit-hack.php, tests/fixtures/drupal/modules/drush_command/src/Commands/TestDrushCommands.php, tests/src/DeprecationRulesTest.php, tests/src/DrupalIntegrationTest.php, tests/src/DrushIntegrationTest.php
This moves from TravisCI to GitHub Actions. It also ensures we're testing on D9.
PHP8 was skipped due to `drupal/core-dev-pinned` referencing `phar-io/manifest:1.0.3` which does not support PHP 8. However, using `drupal/core-dev` would allow `phar-io/manifest:^2.0`. Moving that to another PR.
=> Improve test matrix for D8 + D9

.circleci/config.yml, .github/workflows/php.yml, composer.json, src/Drupal/ServiceMap.php
Unblocks #150
drupal/core-dev-pinned conflicts on PHP8 due to phar-io/manifest:1.0.3, we need ^2
=> Add PHP8 testing to the matrix

.github/workflows/php.yml, src/Drupal/DrupalAutoloader.php, src/Rules/Drupal/GlobalDrupalDependencyInjectionRule.php, tests/fixtures/drupal/modules/module_with_tests/tests/src/Kernel/DrupalStaticCallTest.php, tests/src/DrupalIntegrationTest.php
See #167. Tries using `getInterfaceNames` over `classImplements` to handle missing PHPUnit
=> Check getInterfaceNames over implementsInterface

README.md, composer.json, extension.neon
The two can't be used together and `excludes_analyse` was deprecated in phpstan 0.12.65. See:
- https://phpstan.org/user-guide/ignoring-errors#excluding-whole-files
- https://newreleases.io/project/github/phpstan/phpstan/release/0.12.65
- https://github.com/phpstan/phpstan/issues/3749#issuecomment-754749316
Fixes #179
=> Use excludePath instead of excludes_analyse

src/Rules/Deprecations/DeprecatedAnnotationsRuleBase.php, tests/fixtures/drupal/modules/phpstan_fixtures/phpstan_fixtures.module
=> Ensure anonymous classes are not reflected

src/Drupal/DrupalAutoloader.php
Remove unnecessary class map entry for PhpunitCompatibilityTrait, drop `require_once` for bootstrap.php to avoid any odd side effects later on.
Came from: https://www.drupal.org/project/upgrade_status/issues/3231048. Waiting for feedback before merge.
=> Clean up PHPUnit bootstrap inclusion

src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php, tests/src/Rules/BrowserTestBaseDefaultThemeRuleTest.php
Fixes #198
Only errors for `defaultTheme` when a testing profile is used.
=> Only error on defaultTheme for testing profiles

src/Reflection/EntityFieldsViaMagicReflectionExtension.php, tests/src/Reflection/EntityFieldsViaMagicReflectionExtensionTest.php
So here is a thing.
If a variable was declared to be just the FieldItemListInterface, phpstan-drupal would not allow it to access things like ->value, since we require it to implement interface FieldItemListInterface. Which returns false if the variable is literally that interface.
You would need at lest level 2 to get this error.
An example:
```
/** @var \Drupal\Core\Field\FieldItemListInterface $field */
$field = $node->get('my_field');
$value = $field->value; // <- this fails with Access to an undefined property Drupal\Core\Field\FieldItemListInterface::$value
```
You don't actually need to typehint the field either, because the ->get method is supposed to return FieldItemListInterface.
```
$field = $node->get('my_field');
$value = $field->value; // <- fails with Access to an undefined …
```
=> Allow magic methods for variables of type FieldItemListInterface

extension.neon, src/Internal/NamespaceCheck.php, src/Rules/Classes/ClassExtendsInternalClassRule.php, tests/fixtures/drupal/modules/module_with_internal_classes/module_with_internal_classes.info.yml, tests/fixtures/drupal/modules/module_with_internal_classes/src/Foo/ExternalClass.php, tests/fixtures/drupal/modules/module_with_internal_classes/src/Foo/InternalClass.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Internal/DoesNotExtendsAnyClass.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Internal/ExtendsDrupalCoreExternalClass.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Internal/ExtendsDrupalCoreInternalClass.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Internal/ExtendsDrupalCorePHPStanDrupalTestsInternalClass.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Internal/ExtendsInternalClass.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Internal/ExtendsPHPStanDrupalModuleWithInternalClassesExternalClass.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Internal/ExtendsPHPStanDrupalModuleWithInternalClassesInternalClass.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Internal/ExtendsRootInternalClass.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Internal/InternalClass.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Internal/WithAnAnonymousClassExtendingAnInternalClass.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/InternalClass.php, tests/src/Rules/ClassExtendsInternalClassRuleTest.php
See #183
In this PR, a shared namespace for Drupal starts with `Drupal\project_name`.
It means:
* a class inside `Drupal\Core` can extends an internal class from `Drupal\Core`
* a class inside `Drupal\my_module` can extends an internal class from `Drupal\my_module`
* a class inside `Drupal\my_module` cannot extends an internal class from `Drupal\Core` or `\Drupal\another_module`
* a class inside `Drupal\Component` cannot extends an internal class from `Drupal\Core` or `\Drupal\another_module`
* a class inside `Drupal\Core` cannot extends an internal class from `Drupal\Component` or `\Drupal\another_module`
* etc..
For the part detecting calls to internal methods, I think it can be handled in another PR 🤔
=> Detect when a class extends a class that has been flagged as @internal

extension.neon, src/Drupal/DrupalAutoloader.php, src/Drupal/Extension.php, src/Drupal/ExtensionMap.php, src/Rules/Drupal/LoadIncludeBase.php, src/Rules/Drupal/LoadIncludes.php, src/Rules/Drupal/ModuleLoadInclude.php, tests/fixtures/drupal/modules/module_with_dependencies/module_with_dependencies.info.yml, tests/fixtures/drupal/modules/module_without_dependencies/module_without_dependencies.info.yml, tests/src/Drupal/ExtensionTest.php, tests/src/Rules/LoadIncludesRuleTest.php, tests/src/Rules/ModuleLoadIncludeRuleTest.php
See #249 
Just to open discussion
=> Make the discovered Drupal extensions accessible via a service

src/Reflection/EntityFieldsViaMagicReflectionExtension.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Entity/ReflectionEntityTest.php, tests/src/Reflection/EntityFieldsViaMagicReflectionExtensionTest.php, tests/src/Type/EntityPropertyTypeTest.php, tests/src/Type/data/entity-properties.php
Fixes #172 and possibly another issue, since I'm sure I stole it from somewhere?
Updates EntityFieldsViaMagicReflectionExtensionTest to test annotated properties are skipped in the same way as explicit properties, adding an annotation to ReflectionEntityTest fixture.
No integration test to make sure annotations are actually respected, not sure if this is needed, or how to implement?
=> Respect @property annotations on Entity classes

extension.neon, src/Reflection/EntityFieldMethodsViaMagicReflectionExtension.php, src/Reflection/EntityFieldsViaMagicReflectionExtension.php, src/Reflection/FieldItemListMethodReflection.php, src/Reflection/FieldItemListPropertyReflection.php, tests/src/Reflection/EntityFieldMethodsViaMagicReflectionExtensionTest.php
OK, so this PR adds a bit to the legacy that is allowed things on a field item.
Currently we just assume that if an object is of the type FieldItemListInterface (or super type of) then we can access the properties entity, value and target_id.
Technically this might be true, as accessing ->entity on a text item would probably just give you null? But my claim is that if we are blindly allowing things that might be from another field, we might as well allow methods that might be on another field. For example ::referencedEntities.
Ideally I would see some sort of elaborate entity field mapping thing, where you can actually specify that field_coupon would be an entityreference item (and its class) but that's more of a refactor than this PR (and my time) allows. So here is a stab at allowing …
=> Allow ::referencedEntities on field items

composer.json
Hi @mglaman
This PR fixes #263. It also removes `phpstan-deprecation-rule` from the list, as the package is part of the dev dependencies.
Hope this helps!
=> Add phpstan prophecy suggestion

composer.json, src/Drupal/DrupalAutoloader.php
There's no need to nette/finder - symfony has a finder that's already part of Drupal core and included by many many things...
```
composer/composer                2.2.4      requires   symfony/finder (^2.8.52 || ^3.4.35 || ^4.4 || ^5.0 || ^6.0)
consolidation/annotated-command  4.5.1      requires   symfony/finder (^4.4.8|^5|^6)
consolidation/output-formatters  4.2.1      requires   symfony/finder (^4|^5|^6)
consolidation/robo               3.0.7      requires   symfony/finder (^4.4.9 || ^5 || ^6)
consolidation/site-alias         3.1.3      requires   symfony/finder (~2.3|^3|^4.4|^5)
drupal/core-dev                  9.3.2      requires   symfony/finder (^4.4)
drush/drush                      10.6.2     requires   symfony/finder (^3.4 || ^4.0 || ^5)
enlightn/security-checker        v1.9.0 …
```
=> Use a dependency that is already present and doesn't add new dependency

src/Rules/Drupal/RenderCallbackRule.php, tests/fixtures/drupal/modules/pre_render_callback_rule/src/LazyBuilderWithConstant.php, tests/fixtures/drupal/modules/pre_render_callback_rule/src/RenderArrayWithPreRenderCallback.php, tests/src/Rules/PreRenderCallbackRuleTest.php
Fixes #301
- Handle concatenation of static::class with string as callback
- Properly handle lazy builder callbacks
=> Fix #lazy_builder callback analysis and static::class concatenation warning

src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php
Avoid inspecting classes we know aren't tests or Functional/Browser tests.
Fixes https://github.com/mglaman/phpstan-drupal/issues/318
=> Optimize BrowserTestBaseDefaultThemeRule

src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php
Uses a namespace check before performing reflections in BrowserTestBaseDefaultThemeRule. This seems to shave 3-5s off of the sample set of analyzing the `action` module.
Fixes #318
=> BrowserTestBaseDefaultThemeRule namespace check

extension.neon, stubs/Twig/functions.stub
twig_escape_filter is a hidden function inside a class file so not discovered
though normal discovery or autoloading so providing scan stub allows its use
to be analyzed.
Fixes #310
=> Provide a stub for twig_escape_filter

extension.neon, phpstan.neon, tests/src/Rules/GetDeprecatedServiceRuleTest.php
Fixes #325. The \Drupal::VERSION constant changes based on what is installed.
=> Mark \Drupal::VERSION as a dynamic constant

src/Rules/Deprecations/AccessDeprecatedConstant.php, tests/fixtures/drupal/modules/phpstan_fixtures/phpstan_fixtures.module, tests/src/Rules/AccessDeprecatedConstantTest.php
Fixes #326. Accountsa for current Drupal version.
=> Perform \Drupal::VERSION check for deprecated constants

extension.neon, src/Rules/Deprecations/ConditionManagerCreateInstanceContextConfigurationRule.php, tests/fixtures/drupal/modules/phpstan_fixtures/phpstan_fixtures.module, tests/src/Rules/ConditionManagerCreateInstanceContextConfigurationRuleTest.php
=> Rule for ConditionManager::createInstance() when 'context' is passed as array key

extension.neon, stubs/Drupal/file/Plugin/Field/FieldType/FileItem.stub, stubs/Drupal/file/Plugin/Field/FieldType/FileUriItem.stub, tests/src/Type/data/field-types.php
As the title says, adds stubs for field types defined by the core file module.
=> Add field type stubs for file module

stubs/Drupal/Core/Field/Plugin/Field/FieldType/EntityReferenceItem.stub, tests/src/Type/data/field-types.php
If you delete the entity that is referenced by an ER field, the entity property will return NULL
Code needs to be aware of that and handle it.
Without this change, code that is being defensive for when entity is NULL shows linting errors on phpstan level 6
=> The entity property can return NULL

composer.json, src/Drupal/EntityDataRepository.php, tests/src/Type/EntityTypeManagerGetStorageDynamicReturnTypeExtensionTest.php, tests/src/Type/data/bug-377.php, tests/src/Type/data/container.php, tests/src/Type/data/drupal-class-resolver.php, tests/src/Type/data/drupal-service-static.php, tests/src/Type/data/entity-type-manager.php
Fixes #377
\mglaman\PHPStanDrupal\Drupal\EntityDataRepository::resolveFromStorage does not work correctly for generic storage types. If the entity storage if EntityStorageInterface then the first entity definition is selected.
=> resolveFromStorage does not respect default phpDoc for generic storage interface

README.md, composer.json, extension.neon, rules.neon, tests/fixtures/config/phpunit-drupal-phpstan.neon
Fixes #295
Allows manual configuration without extension-installer and cherry-picking rules.
=> Move rules to `rules.neon`

.github/workflows/php.yml, tests/fixtures/config/phpunit-drupal-phpstan.neon
Fixes HEAD for PHPStan 1.6.0+ on tests which use bleedingEdge until #399 is finished.
=> Enable richParserNodeVisitor for tests

src/Rules/Drupal/RenderCallbackRule.php, tests/fixtures/config/phpunit-drupal-phpstan.neon, tests/src/Rules/RenderCallbackRuleTest.php
Fixes #399 by removing calls to `parent` attributes.
=> Explicit allowed class checks for #lazy_builder

src/Type/ContainerDynamicReturnTypeExtension.php, src/Type/DrupalServiceDynamicReturnTypeExtension.php, tests/fixtures/drupal/modules/service_map/service_map.services.yml, tests/src/Type/data/container.php, tests/src/Type/data/drupal-class-resolver.php, tests/src/Type/data/drupal-service-static.php
According to [this docs page](https://www.drupal.org/docs/drupal-apis/services-and-dependency-injection/services-and-dependency-injection-in-drupal-8#s-defining-services-by-fully-qualified-name-of-php-namespace) using the fully qualified class name when interacting with services is a supported approach.
This PR adds the correct return type hint when this approach is used.
=> add support for class string service ids

composer.json, src/Rules/Drupal/RenderCallbackRule.php, tests/src/Rules/RenderCallbackRuleTest.php
Discussed briefly in Slack with @mglaman - this would remove the false positives in https://www.drupal.org/project/drupal/issues/3259716 and allow `static::class . '::methodName'` to be resolved correctly.
Fixes #371
=> Allow static::class . '::methodName' concatenation in lazy builders.

src/Rules/Deprecations/SymfonyCmfRoutingInClassMethodSignatureRule.php, tests/src/Rules/data/symfony-cmf-routing.php
Fixes incorrect errors reported in #445
=> SymfonyCmfRoutingInClassMethodSignatureRule stop using isSuperOf

src/Rules/Drupal/RenderCallbackRule.php, stubs/Drupal/Core/Cache/CacheableDependencyInterface.stub, stubs/Drupal/Core/Cache/CacheableMetadata.stub, stubs/Drupal/Core/Cache/RefinableCacheableDependencyInterface.stub, stubs/Drupal/Core/Render/AttachmentsInterface.stub, stubs/Drupal/Core/Render/BubbleableMetadata.stub, stubs/Drupal/filter/FilterProcessResult.stub, tests/src/Rules/RenderCallbackRuleTest.php
Fixes #449. 
If the node is callable or callable-string, trust it. Fixes analysis on FilterProcessResult.
=> Add generic callable check for RenderCallbackRule

stubs/Drupal/Core/Field/EntityReferenceFieldItemListInterface.stub, tests/fixtures/drupal/modules/phpstan_fixtures/src/Entity/ReflectionEntityTest.php, tests/src/Type/data/entity-properties.php
Allow `\Drupal\Core\Field\EntityReferenceFieldItemListInterface::referencedEntities` to work with generic.
E.g practical usage with entity bundle classes:
```php
/**
* @property  \Drupal\Core\Field\EntityReferenceFieldItemListInterface<Drupal\mycontent\Entity\BlockContent\MyBlockContent> $things
*/
class Entity {
/**
* @return array<\Drupal\mycontent\Entity\BlockContent\MyBlockContent>
*/
public function getThings(): array {
return $this->things->referencedEntities();
}
}
```
Currently, PHPStan error prints:
> phpstan: Method Entity::getThings() should return array<\Drupal\mycontent\Entity\BlockContent\MyBlockContent> but returns array<Drupal\Core\Entity\EntityInterface>.
PR resolves this.
=> Allow EntityReferenceFieldItemListInterface::referencedEntities to work with generic

src/Type/EntityQuery/EntityQueryType.php, tests/src/Rules/EntityQueryHasAccessCheckRuleTest.php, tests/src/Rules/data/bug-475.php, tests/src/Rules/data/bug-475b.php
Fixes #475
The EntityQueryType was getting cached in function scope for a `condition` call and because it wasn't handled by dynamic return it reused. So if you had `condition` before `accessCheck` and then later on after it, the latter one could fail because it would return the cached without access check and there would be no subsequent access check (it happens before).
Added test case.
Still examining why this doesn't occur in class scope but it seems phpstan has additional cache key when it is just not sure of its granularity.
=> fix: Fix unpredictable false positive/negative of missing entity access check in function scope due to cache key conflict

extension.neon, src/Type/EntityQuery/AccessCheckTypeSpecifyingExtension.php, tests/src/Rules/EntityQueryHasAccessCheckRuleTest.php, tests/src/Rules/data/bug-496.php
=> False negative accessCheck failure on non-chained entity queries

src/Rules/Drupal/LoadIncludeBase.php, src/Rules/Drupal/LoadIncludes.php, tests/src/Rules/LoadIncludesRuleTest.php, tests/src/Rules/data/bug-516.php
Fixes https://github.com/mglaman/phpstan-drupal/issues/516
=> Ignore LoadIncludes rule if module and file name unknown

src/Rules/Drupal/RenderCallbackRule.php, tests/src/Rules/RenderCallbackRuleTest.php, tests/src/Rules/data/bug-543.php
=> Support concatenated callables in RenderCallbackRule

src/Reflection/EntityFieldReflection.php, src/Reflection/EntityFieldsViaMagicReflectionExtension.php, stubs/Drupal/Core/Entity/EntityChangedInterface.stub, stubs/Drupal/Core/Entity/EntityPublishedInterface.stub, stubs/Drupal/Core/Entity/RevisionLogInterface.stub, stubs/Drupal/Core/Entity/RevisionableInterface.stub, stubs/Drupal/node/NodeInterface.stub, stubs/Drupal/node/user/EntityOwnerInterface.stub, tests/src/Reflection/EntityFieldsViaMagicReflectionExtensionTest.php, tests/src/Type/EntityPropertyTypeTest.php, tests/src/Type/data/book-module.php
As of Drupal 9.5, 10.0, and 10.1, the book module adds a "book" property to Node instances that have been enabled as books.
PHPStan is not aware of this and thus reports messages like `Property Drupal\node\NodeInterface::$book (Drupal\Core\Field\FieldItemListInterface) does not accept array.`
Tell PHPStan to expect a `book` property on Nodes that is an array.
I wanted to be more specific about what's in this array, but I'm not certain how to do that in PHPStan - its API documentation is somewhat minimal. If you have suggestions, I would be happy to update this merge request.
The `book` property is an array that contains the following keys/types:
| Array key | Data type |
|--------|--------|
| `nid` | `int` (or `numeric-string`) |
| `bid` | `int` (or `numeric-string`) |
| `pid` | `int` (or …
=> Make EntityFieldReflection aware of the book property added by book.module.

src/Rules/Drupal/GlobalDrupalDependencyInjectionRule.php, tests/src/Rules/GlobalDrupalDependencyInjectionRuleTest.php, tests/src/Rules/data/bug-515.php
=> Allow static calls to \Drupal in \Drupal\TestSite\TestSetupInterface

stubs/Drupal/Core/Entity/TranslatableInterface.stub, tests/src/Type/ContentEntityTranslationTypeTest.php, tests/src/Type/data/content-entity-translation.php
This is a stub for the `TranslatableInterface`. Note that this stub will be unnecessary for Drupal 10.1+ (see https://www.drupal.org/project/drupal/issues/3269177). Nevertheless, it may be useful for users that run a prior version of Drupal.
This change is a little bit aggressive because it creates a stub for the `TranslatableInterface` directly, although only tests for content entities are provided. We could be more passive by basing the stub on the `ContentEntityBase`.
=> Add translatable interface stub for content entities

src/Rules/Drupal/PluginManager/PluginManagerSetsCacheBackendRule.php, tests/src/Rules/PluginManagerSetsCacheBackendRuleTest.php, tests/src/Rules/data/plugin-manager-cache-backend.php
**Motivation**
In my project I'm getting:
> Missing cache backend declaration for performance.
with a plugin manager having the cache backend line in the constructor:
```php
$this->setCacheBackend($cache_backend, "mymodule_{$type}_plugins");
```
where `$type` is passed in constructor's signature, same as in Views plugin manager.
**Proposed changes**
This PR
**Alternatives considered**
None.
**Testing steps**
Unfortunately, for some mysterious reasons, I can't replicate this in the test from phpstan-drupal. I'm missing something. But applying the PR as patch to my project solves the issue.
I'm using
* PHPStan 1.10.25
* mglaman/phpstan-drupal 1.1.36
=> Check also for Node\Scalar\Encapsed

phpstan.neon, stubs/Drupal/Core/Entity/BundleEntityStorageInterface.stub, stubs/Drupal/Core/Entity/ContentEntityStorageBase.stub, stubs/Drupal/Core/Entity/ContentEntityStorageInterface.stub, stubs/Drupal/Core/Entity/DynamicallyFieldableEntityStorageInterface.stub, stubs/Drupal/Core/Entity/EntityHandlerBase.stub, stubs/Drupal/Core/Entity/EntityHandlerInterface.stub, stubs/Drupal/Core/Entity/EntityStorageBase.stub, stubs/Drupal/Core/Entity/FieldableEntityStorageInterface.stub, stubs/Drupal/Core/Entity/RevisionableStorageInterface.stub, stubs/Drupal/Core/Entity/TranslatableRevisionableStorageInterface.stub, stubs/Drupal/Core/Entity/TranslatableStorageInterface.stub, tests/src/Rules/RevisionableStorageInterfaceStubTest.php, tests/src/Rules/data/bug-586.php
fixes #586
```
// RevisionableStorageInterface before TranslatableStorageInterface so that its definition of
// `loadRevision` is cached by PHPStan's reflection first. Otherwise PHPStan's reflection caches
// the PhpDoc from `EntityStorageInterface::loadRevision`.
//
// This is fragile and relies on `ContentEntityStorageInterface` only implementing this interface.
interface TranslatableRevisionableStorageInterface extends RevisionableStorageInterface, TranslatableStorageInterface {
}
// Remove extension of `EntityStorageInterface` so that `TranslatableRevisionableStorageInterface`
// is properly processed.
interface ContentEntityStorageInterface extends TranslatableRevisionableStorageInterface {
}
```
This can't be fixed until Drupal core fixes its interface declarations. …
=> Improve RevisionableStorageInterface stub

src/Type/ContainerDynamicReturnTypeExtension.php, tests/src/Type/DrupalContainerDynamicReturnTypeTest.php, tests/src/Type/data/container-optional.php
When developing modules that interact with optional modules it is useful to pass the `ContainerInterface::NULL_ON_INVALID_REFERENCE` second arg and do a null check rather than cumbersome exception handling 
This change adds `null` to the return type of any `$container->get` method calls that explicitly state it may return null
This also improves handling of `$container->get` with any second arg in general, as the second arg would disable the return type extension, causing it to fallback to the `object|null` return type on the ContainerInterface even though the module is likely available due to `require-dev` and this extension could provide a better type.
Looking at the [drupal source](https://github.com/drupal/drupal/blob/1325be71ae78c43818dd84dd2e542b21559435af/core/lib/Drupal/Component/D …
=> Add null to the container get method return type when ContainerInterace::NULL_ON_INVALID_REFERENCE is passed as the second argument.

src/Drupal/DrupalServiceDefinition.php, tests/src/ServiceMapFactoryTest.php
This should fix the issues reported in https://github.com/apigee/apigee-edge-drupal/pull/969
=> Use TypeCombinator::union() to combine decorated service classes.

src/Drupal/DrupalAutoloader.php
This makes it easier to debug the drupal_root parameter for discovery issues.
=> Display raw drupal_root parameter for better debugging

src/Drupal/DrupalAutoloader.php, src/Rules/Deprecations/DeprecatedHookImplementation.php, tests/fixtures/drupal/modules/module_with_deprecated_hooks/module_with_deprecated_hooks.api.php, tests/fixtures/drupal/modules/module_with_deprecated_hooks/module_with_deprecated_hooks.info.yml, tests/fixtures/drupal/modules/module_with_deprecated_hooks/module_with_deprecated_hooks.module, tests/src/Rules/DeprecatedHookImplementationTest.php
This will analyse hook implementations in `.inc` and `.module` files. It detects a hook by looking at the pattern `mymodule_[hook]` which is detected from the file-name the function is in.
It will replace `mymodule` with `hook` and then try to find a function with that name. For this to work PHPStan Drupal's `DrupalAutoloader` class must be adjusted to load `.api.php` files as well so that the hooks can be discovered. In testing on the Open Social code-base this did not cause any issues.
The rule will provide the deprecation message in the error if it's provided, if no deprecation message was provided (i.e. a lonesome `@deprecated` tag) then the hook will simply be shown as deprecated without advice.
Fixes #126
=> Implement a rule to check deprecated hook implementations

src/Rules/Classes/ClassExtendsInternalClassRule.php
Whilst having a poke around in the code for the sake of curiosity, i noticed this expression that is missing a return and as such does nothing.
If i look at the commit that introduced the issue, it appears as though the `->tip` calls were added in the same commit, so i'm not sure if the `return` is intended to be there, or if the entire conditional is now redundant and not necessary. Interestingly the tests don't change with or without the `return` so it's hard to say whether or not it should be there?
Perhaps given that it's been like this for ~3 years the correct fix is to remove the conditional altogether? If that is preferred let me know and i can update the pull request.
=> Add missing return in ClassExtendsInternalClassRule.

src/Rules/Deprecations/SymfonyCmfRoutingInClassMethodSignatureRule.php, src/Rules/Drupal/TestClassesProtectedPropertyModulesRule.php
PHPStan added the ability to access reflection objects from many of it's virtual nodes which guarantees they will be there, avoiding the need to do these checks.
=> Simplify access to reflections in SymfonyCmfRoutingInClassMethodSignatureRule and TestClassesProtectedPropertyModulesRule.

src/Rules/Classes/ClassExtendsInternalClassRule.php, src/Rules/Deprecations/AccessDeprecatedConstant.php, src/Rules/Deprecations/ConditionManagerCreateInstanceContextConfigurationRule.php, src/Rules/Deprecations/DeprecatedAnnotationsRuleBase.php, src/Rules/Deprecations/DeprecatedHookImplementation.php, src/Rules/Deprecations/GetDeprecatedServiceRule.php, src/Rules/Deprecations/StaticServiceDeprecatedServiceRule.php, src/Rules/Deprecations/SymfonyCmfRouteObjectInterfaceConstantsRule.php, src/Rules/Deprecations/SymfonyCmfRoutingInClassMethodSignatureRule.php, src/Rules/Drupal/Coder/DiscouragedFunctionsRule.php, src/Rules/Drupal/EntityQuery/EntityQueryHasAccessCheckRule.php, src/Rules/Drupal/GlobalDrupalDependencyInjectionRule.php, src/Rules/Drupal/LoadIncludeBase.php, src/Rules/Drupal/LoadIncludes.php, src/Rules/Drupal/ModuleLoadInclude.php, src/Rules/Drupal/PluginManager/AbstractPluginManagerRule.php, src/Rules/Drupal/PluginManager/PluginManagerSetsCacheBackendRule.php, src/Rules/Drupal/RenderCallbackRule.php, src/Rules/Drupal/RequestStackGetMainRequestRule.php, src/Rules/Drupal/TestClassesProtectedPropertyModulesRule.php, src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php
This change allows phpstan to statically verify that the rules work correctly without having to get `assert()` involved, as `assert()` is a finicky beast whose implications can change based on the php configuration of the system it is run on.
=> Add implements generics to all Rule implementations and remove associated assert() calls.

extension.neon, rules.neon, src/Rules/Drupal/Coder/FormNoPrivatePropertiesRule.php, src/Rules/Drupal/DependencySerializationTraitPropertyRule.php, tests/src/Rules/DependencySerializationTraitPropertyRuleTest.php, tests/src/Rules/data/dependency-serialization-trait.php
Adds a check for all FormInterface implementing classes that private variables are no longer allowed
See #730 for context and discussion 
Fixes #730
=> Add DependencySerializationTraitPropertyRule

src/Drupal/DrupalAutoloader.php
Drupal now allows services.yml to contain YAML tags such as `!tagged_iterator`:
https://www.drupal.org/project/drupal/issues/3414208
https://www.drupal.org/node/3436859
This however crashes the DrupalAutoloader code:
https://git.drupalcode.org/project/drupal/-/jobs/1217562
`Symfony\Component\Yaml\Exception\ParseException thrown in /builds/project/drupal/vendor/symfony/yaml/Inline.php on line 775 while loading bootstrap file /builds/project/drupal/vendor/mglaman/phpstan-drupal/drupal-autoloader.php: Tags support is not enabled. Enable the "Yaml::PARSE_CUSTOM_TAGS" flag to use "!tagged_iterator" at line 635 (near "arguments: [!tagged_iterator module_install.uninstall_validator]").`
=> Allow services.yml to contain custom tags

src/Drupal/ServiceMap.php
When running phpstan, I was getting
TypeError thrown in /var/www/html/vendor/mglaman/phpstan-drupal/src/Drupal/DrupalServiceDefinition.php on line 55 while loading bootstrap file /var/www/html/vendor/mglaman/phpstan-drupal/drupal-autoloader.php: mglaman\PHPStanDrupal\Drupal\DrupalServiceDefinition::setDeprecated(): Argument #2 ($template) must be of type ?string, array given, called in /var/www/html/vendor/mglaman/phpstan-drupal/src/Drupal/ServiceMap.php on line 63
Also, the deprecated message is not too helpful:
"deprecated" => "The "%service_id%" service is deprecated in drupal:9.0.0 and is removed from drupal:20.0.0. This is a test."
This would be replaced by Symfony's dependecy-injection Definition class. As phpstan pulls them directly from the yaml file, we should do the replacement.
=> Fixing TypeError and deprecated message

bleedingEdge.neon, extension.neon, src/Drupal/DrupalAutoloader.php
Fixes #770
1. Added new options to bleeding edge. Current behaviour is the same.
2. Trigger deprecation notice when using old parameter, did not add a version since i dont know when it will be removed
3. Added defaults as per related issue. Behaviour is the same, but can be specified.
4. Wanted to add a test for a core module, but not sure how so i didnt.
=> Seperate core and contrib api files

src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php
This should include the exclusion for the new class to match the now deprecated InstallerExistingConfigTestBase.
- fixes #780
=> Add new class to exclusion [#780]

src/Drupal/DrupalAutoloader.php, src/Drupal/ServiceMap.php
=> Add support for shorthand service definition syntax

src/Type/InspectorTypeExtension.php, tests/src/Type/data/inspector.php
As discussed in Slack: https://drupal.slack.com/archives/C033S2JUMLJ/p1744383402099899?thread_ts=1744246451.941499&cid=C033S2JUMLJ, the current Inspector implementation doesn't handle negation at all.
For example:
```php
$array = mixed_function();
assertType('mixed', $array);
Inspector::assertAll(fn (array $i): bool => TRUE, $array);
assertType('iterable', $array);
```
After passing `Inspector::assertAll(fn (array $i): bool => TRUE, $array);` line, PHPStan would think it is always iterable, even if it is not passed `::assertAll()` and the result was `FALSE`. This works fine with `assert()`, but breaks under other conditions, for example:
```php
$array = mixed_function();
assertType('mixed', $array);
if (!Inspector::assertAll(fn (array $i): bool => TRUE, $array)) { …
```
=> 2.x: Fix negation types for Inspector

src/Type/InspectorTypeExtension.php, tests/src/Type/data/bug-852.php, tests/src/Type/data/inspector.php
=> 1.x: Fix negation types for Inspector

src/Type/InspectorTypeExtension.php, tests/src/Rules/ImpossibleCheckTypeStaticMethodCallRuleTest.php, tests/src/Rules/data/bug-857.php, tests/src/Type/InspectorTypeExtensionTest.php, tests/src/Type/data/bug-857.php
=> 1.x: Fix assertAll causes staticMethod.alreadyNarrowedType

src/Type/InspectorTypeExtension.php, tests/src/Rules/ImpossibleCheckTypeStaticMethodCallRuleTest.php, tests/src/Rules/data/bug-857.php, tests/src/Type/InspectorTypeExtensionTest.php, tests/src/Type/data/bug-857.php
=> 2.x: Fix assertAll causes staticMethod.alreadyNarrowedType

tests/src/DrushIntegrationTest.php
The latest CI build has started to fail. You can view the details here: https://github.com/mglaman/phpstan-drupal/actions/runs/14497424898/job/40668597915#step:6:18
PHPStan has recently changed the constructor signature for `\PHPStan\Rules\Functions\CallToNonExistentFunctionRule::__construct`. 
You can view the changes here: https://github.com/phpstan/phpstan-src/blame/db66d83f6ae3dadec529dd53bcde250344c2230f/src/Rules/Functions/CallToNonExistentFunctionRule.php#L23
It's available since 2.1.12: https://github.com/phpstan/phpstan-src/releases/tag/2.1.12
=> Fix DrushIntegrationTest

composer.json, phpstan.neon, stubs/Drupal/Component/Plugin/DependentPluginInterface.stub, stubs/Drupal/Component/Plugin/DerivativeInspectionInterface.stub, stubs/Drupal/Component/Plugin/PluginBase.stub, stubs/Drupal/Core/Field/EntityReferenceFieldItemList.stub, stubs/Drupal/Core/Field/FieldItemList.stub, stubs/Drupal/Core/Field/FormatterBase.stub, stubs/Drupal/Core/Field/FormatterInterface.stub, stubs/Drupal/Core/Field/Plugin/Field/FieldFormatter/EntityReferenceFormatterBase.stub, stubs/Drupal/Core/Field/PluginSettingsBase.stub, stubs/Drupal/Core/Field/PluginSettingsInterface.stub, stubs/Drupal/Core/Plugin/ContainerFactoryPluginInterface.stub, stubs/Drupal/Core/Plugin/PluginBase.stub, stubs/Drupal/Core/TypedData/Plugin/DataType/ItemList.stub, tests/src/Generics/EntityReferenceFieldItemListGenericTest.php, tests/src/Generics/EntityReferenceFormatterBaseGenericTest.php, tests/src/Generics/EntityReferenceItemGenericTest.php, tests/src/Generics/FormatterBaseGenericTest.php, tests/src/Generics/FormatterInterfaceGenericTest.php, tests/src/Generics/data/entity-reference-field-item-list.php, tests/src/Generics/data/entity-reference-formatter-base.php, tests/src/Generics/data/entity-reference-item.php, tests/src/Generics/data/formatter-base.php, tests/src/Generics/data/formatter-interface.php
From #822: This PR changes FormatterStub to be a proper generic instead of narrowing types for others.
**Conflict with #845.**
=> Make FormatterInterface stub generic

src/Type/InspectorTypeExtension.php, tests/src/Type/data/inspector.php
While I've worked and played with different cases for #870, I've improved test cases and unified `InspectorTypeExtension` logic.
The main changes:
* The extension variables are now named identically across all methods, and their names are more clear about what information they contain. For example: `$traversable` (traversable what?) → `$traversableArg` and `$traversableInfo` (too obscure) → `$traversableType`.
* Add the `$newType` variable for the return type, so the `return` statement is much simpler and doesn't contain any logic.
* I improved test cases so they test `mixed` and `array` types at the same time. Using the ternary operator in test cases makes them much simpler and easier to read, and makes the code smaller.
I don't mind if you decide not to merge it. It was done anyway, so …
=> Improve the InspectorTypeExtension and its tests

stubs/Drupal/Core/Entity/RevisionableStorageInterface.stub
Same as #894, I did have a stub for `RevisionableStorageInterface` [with this change in scheduled_transitions modul](https://git.drupalcode.org/project/scheduled_transitions/-/blob/2.8.x/stubs/Stubs.stub?ref_type=heads#L33)e, but it is no longer taking effect because phpstan-drupal prevents it.
=> IDs can be strings, `RevisionableStorageInterface::loadRevision` should accept string ids

composer.json
>  Implicitly marking parameter $filesystem as nullable is deprecated
> Composer/Installers/Installer.php:136
=> Allow installers v2 so we can get rid of PHP 8.4 errors

src/Type/EntityIdNarrowedByNew.php, tests/src/Type/data/entity.php
Fixes a bug with #900 reported in https://www.drupal.org/project/experience_builder/issues/3539676 by @larowlan
If the standard return type of string|int|null was narrowed to something smaller, like int|null, then we should not return string|int, we should return int.
=> 🐛 Narrow only by existing return types
