composer.json, extension.neon, src/DependencyInjection/DrupalExtension.php, src/Drupal/Bootstrap.php, src/Drupal/DrupalServiceDefinition.php, src/Drupal/ServiceMap.php, src/Drupal/ServiceMapFactory.php, src/Drupal/ServiceMapFactoryInterface.php, src/Type/ServiceDynamicReturnTypeExtension.php
This serves as a beginning and basic implementation. There needs to be testing for better guarantees this works.
=> Container service return type support

composer.json, src/DependencyInjection/DrupalExtension.php, src/Drupal/Bootstrap.php
Fixes #16 and replaces #19 
Signed-off-by: Jibran Ijaz <jibran.ijaz@gmail.com>
=> [#16] Use webflo/drupal-finder to find docroot.

src/DependencyInjection/DrupalExtension.php, src/Drupal/Bootstrap.php
Fixes #24.
Signed-off-by: Jibran Ijaz <jibran.ijaz@gmail.com>
=> [#24] Adds profiles namespaces.

src/DependencyInjection/DrupalExtension.php, src/Drupal/Bootstrap.php
=> Replace getcwd() with global autoloaderInWorkingDirectory

README.md
See https://github.com/phpstan/phpstan#extensibility
=> Link back PHPStan

.travis.yml, extension.neon
=> Add a test that `test/fixtures` should be excluded

.travis.yml, extension.neon, src/Drupal/Bootstrap.php
=> blazy test.module fix

.travis.yml, src/Drupal/Bootstrap.php, tests/fixtures/config/drupal-phpstan.neon, tests/fixtures/config/phpunit-drupal-phpstan.neon
Fixes https://github.com/mglaman/phpstan-drupal/issues/59
=> Fix autoloading of test base classes

src/DependencyInjection/DrupalExtension.php, tests/DrupalIntegrationTest.php, tests/fixtures/config/phpunit-drupal-phpstan.neon
=> Fix config level; prove some failures still exist

src/Drupal/Bootstrap.php, tests/fixtures/drupal/modules/contained_not_initialized/contained_not_initialized.info.yml, tests/fixtures/drupal/modules/contained_not_initialized/contained_not_initialized.install, tests/fixtures/drupal/modules/contained_not_initialized/contained_not_initialized.module, tests/fixtures/drupal/modules/contained_not_initialized/contained_not_initialized.pathauto.inc, tests/fixtures/drupal/modules/contained_not_initialized/contained_not_initialized.post_update.php, tests/fixtures/drupal/modules/contained_not_initialized/contained_not_initialized.search_api.inc, tests/fixtures/drupal/modules/contained_not_initialized/contained_not_initialized.tokens.inc, tests/fixtures/drupal/modules/contained_not_initialized/contained_not_initialized.views.inc, tests/fixtures/drupal/modules/contained_not_initialized/contained_not_initialized.views_execution.inc, tests/src/AnalyzerTestBase.php, tests/src/BootstrapTest.php
=> Add graceful handling of container not being initialized

README.md, composer.json
Fix #74 
Because this is very useful :-)
=> Issue #74: Support phpstan/extension-installer

composer.json
=> Issue #81: Add the type key property.

src/Drupal/Bootstrap.php
=> Include new 8.8.x test namespaces

tests/src/DeprecationRulesTest.php
Get HEAD (almost) passing again.
=> Fix tested deprecation messages for the new format

extension.neon, src/Rules/Deprecations/AccessDeprecatedConstant.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/DeprecatedGlobalConstants.php, tests/src/DeprecationRulesTest.php
=> Detection of deprecated constants

.travis.yml, src/Drupal/DrupalAutoloader.php, tests/src/DrupalIntegrationTest.php
=> Include theme-settings.php

src/Rules/Classes/PluginManagerInspectionRule.php, tests/src/AnalyzerTestBase.php, tests/src/BootstrapTest.php
=> Fix failing HEAD

src/Rules/Deprecations/AccessDeprecatedConstant.php
=> Update list of deprecated Drupal constants

.circleci/config.yml, .travis.yml, phpunit.xml, tests/src/DrupalIntegrationTest.php
=> Resolve memory problems in CI

composer.json, src/Drupal/DrupalAutoloader.php, tests/src/DrupalIntegrationTest.php
Tries to see if latest PHPStan has anything for fixing #143 
Fixes #152 152
=> Remove PHPStan conflict

.github/workflows/php.yml
=> Use bluehorndigital/setup-drupal

extension.neon, src/Rules/Drupal/ModuleLoadInclude.php, tests/fixtures/drupal/modules/module_load_include_fixture/module_load_include_fixture.info.yml, tests/fixtures/drupal/modules/module_load_include_fixture/module_load_include_fixture.module, tests/src/DrupalIntegrationTest.php
=> Handle dynamic file loading with module_load_include

.github/workflows/php.yml, .travis.yml, src/Drupal/DrupalAutoloader.php
=> Weight all test modules higher

tests/src/DrupalIntegrationTest.php
I fixed the various phpunit errors.
=> fix phpunit error in CI

extension.neon, src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php, tests/fixtures/drupal/modules/module_with_tests/tests/src/Functional/DefaultThemeTest.php, tests/fixtures/drupal/modules/module_with_tests/tests/src/Functional/ExtendsDefaultThemeTest.php, tests/fixtures/drupal/modules/module_with_tests/tests/src/Functional/MissingDefaultThemeTest.php, tests/src/Rules/BrowserTestBaseDefaultThemeRuleTest.php
=> Detect undefined defaultTheme property

.github/workflows/php.yml, extension.neon, src/Drupal/DrupalServiceDefinition.php, src/Drupal/ServiceMap.php, src/Rules/Deprecations/AccessDeprecatedConstant.php, src/Rules/Deprecations/GetDeprecatedServiceRule.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Controller/EntityManagerInjectedController.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Plugin/Block/EntityManagerInjectedBlock.php, tests/src/DeprecationRulesTest.php, tests/src/DrupalIntegrationTest.php
=> Allow service definitions to be identified as deprecated

extension.neon, src/Rules/Deprecations/StaticServiceDeprecatedServiceRule.php, src/Type/ContainerDynamicReturnTypeExtension.php, src/Type/DrupalServiceDynamicReturnTypeExtension.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/TestServicesMappingExtension.php, tests/src/DrupalIntegrationTest.php
=> Return type extension for \Drupal::service calls

src/Drupal/DrupalAutoloader.php, tests/fixtures/drupal/modules/service_map/service_map.services.yml
=> Handle shortcut service aliasing

src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php, tests/src/Rules/BrowserTestBaseDefaultThemeRuleTest.php
=> Ignore defaultTheme on abstract test classes

src/Rules/Drupal/LoadIncludes.php, tests/src/Rules/LoadIncludesRuleTest.php
Prevents using inline assert and direct reflection, also fixes crashes
when analzing mocked FormStateInterface
Fixes #232
=> Use isSuperTypeOf to detect if module handler

tests/src/Type/DrupalContainerDynamicReturnTypeTest.php, tests/src/Type/data/container.php, tests/src/Type/data/drupal-service-static.php
=> Test drupal container related type inference

src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php, tests/src/Rules/BrowserTestBaseDefaultThemeRuleTest.php
=> BrowserTestBaseDefaultThemeRule false positives with UpdatePathTests

composer.json
Branch alias is outdated in composer.json
=> Update branch alias in composer.json

tests/src/Type/EntityDynamicReturnTypeTest.php, tests/src/Type/data/entity.php
=> Test EntityInterface return type

README.md, extension.neon, src/Type/EntityStorage/ConfigEntityStorageType.php, src/Type/EntityStorage/ContentEntityStorageType.php, src/Type/EntityStorage/EntityStorageDynamicReturnTypeExtension.php, src/Type/EntityStorage/EntityStorageType.php, src/Type/EntityTypeManagerGetStorageDynamicReturnTypeExtension.php, tests/fixtures/config/phpunit-drupal-phpstan.neon, tests/fixtures/drupal/modules/phpstan_fixtures/src/CustomConfigEntityStorage.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/CustomContentEntityStorage.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Entity/ConfigEntityUsingCustomStorage.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Entity/ConfigEntityUsingDefaultStorage.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Entity/ContentEntityUsingCustomStorage.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Entity/ContentEntityUsingDefaultStorage.php, tests/src/Type/EntityDynamicReturnTypeTest.php, tests/src/Type/data/entity-storage.php, tests/src/Type/data/entity-type-manager.php
=> Support entity class return type extension from entity storage methods

extension.neon, src/Drupal/EntityData.php, src/Drupal/EntityDataRepository.php, src/Type/EntityStorage/EntityStorageDynamicReturnTypeExtension.php, src/Type/EntityTypeManagerGetStorageDynamicReturnTypeExtension.php, tests/fixtures/config/phpunit-drupal-phpstan.neon, tests/src/Type/data/entity-type-manager.php
Uses a service to handle entity type data for dynamic return type extensions.
=> EntityDataRepository for entity type data

src/Drupal/ServiceMap.php, tests/fixtures/drupal/modules/service_map/service_map.services.yml, tests/fixtures/drupal/modules/service_map/src/Override.php, tests/src/ServiceMapFactoryTest.php, tests/src/Type/data/container.php
See https://symfony.com/doc/current/service_container/parent_services.html
=> Support parent definition service

src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php
=> Avoid false positives when PHPUnit doesn't exist.

src/Drupal/ServiceMap.php, tests/fixtures/drupal/modules/service_map/service_map.services.yml, tests/fixtures/drupal/modules/service_map/src/Base.php, tests/fixtures/drupal/modules/service_map/src/Concrete.php, tests/fixtures/drupal/modules/service_map/src/SecondBase.php, tests/src/ServiceMapFactoryTest.php, tests/src/Type/data/container.php
~~The test should fail to reproduce the error~~ Now the test should pass. Sorry for the mistake 😅
=> Fail to map a service with a parent which overrides its parent too

extension.neon, src/Rules/Classes/PluginManagerInspectionRule.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/ExamplePluginManager.php, tests/src/Rules/PluginManagerInspectionRuleTest.php
Faced with the same problem and after some debug I figure out that `new \ReflectionClass($fqn);` return an incorrect class object.
Fixes #142
=> issue #142: resolve incorrect $reflection definition

.github/workflows/php.yml
=> Add 10.0.x to tests

README.md, extension.neon, tests/src/Type/data/entity-type-manager.php
=> Expand list of entity type storages

composer.json
Hi @mglaman
This PR fixes #262 and should be merged after #282.
Hope this helps.
=> Add phpstan/phpstan-phpunit to the suggested packages list

README.md
=> Add documentation for contrib entity mapping

src/Rules/Classes/ClassExtendsInternalClassRule.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/Form/ExtendsContentEntityDeleteForm.php, tests/src/Rules/ClassExtendsInternalClassRuleTest.php
=> Add tips to the extends internal class rule errors

extension.neon, src/Type/AccessibleReturnTypeExtension.php, src/Type/ContainerDynamicReturnTypeExtension.php, src/Type/EntityAccessControlHandlerReturnTypeExtension.php, tests/src/Type/AccessibleReturnTypeExtensionTest.php, tests/src/Type/EntityAccessControlHandlerReturnTypeExtensionTest.php, tests/src/Type/data/accessible.php, tests/src/Type/data/entity-access-control-handler.php
=> Add return type extensions for AccessResult methods

.circleci/config.yml, .github/workflows/php.yml, composer.json
=> Require PHP ^7.4

src/Type/EntityTypeManagerGetStorageDynamicReturnTypeExtension.php, tests/src/Type/data/entity-type-manager.php
Fixes mglaman/phpstan-drupal#299
=> Calling getStorage with a constant does not resolve entity mapped storage class

.circleci/config.yml, src/Rules/Drupal/RenderCallbackRule.php, tests/fixtures/drupal/modules/pre_render_callback_rule/pre_render_callback_rule.module, tests/src/Rules/PreRenderCallbackRuleTest.php
=> Handle controller notation for callbacks

src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php, tests/src/Rules/BrowserTestBaseDefaultThemeRuleTest.php
=> Exclude InstallerExistingConfigTestBase from $defaultTheme rule

src/Rules/Drupal/RenderCallbackRule.php, tests/src/Rules/PreRenderCallbackRuleTest.php
=> Allow non-callable in #lazy_builder if array_intersect_key

src/Type/EntityQuery/EntityQueryCountType.php, src/Type/EntityQuery/EntityQueryDynamicReturnTypeExtension.php, tests/fixtures/drupal/modules/phpstan_fixtures/src/EntityQueryWithAccessRule.php
=> Entity query count and accessCheck order should not matter

.github/workflows/php.yml, composer.json, phpcs.xml, src/Reflection/EntityFieldMethodsViaMagicReflectionExtension.php, src/Reflection/FieldItemListMethodReflection.php, src/Rules/Classes/PluginManagerInspectionRule.php, src/Rules/Deprecations/AccessDeprecatedConstant.php, src/Rules/Deprecations/GetDeprecatedServiceRule.php, src/Rules/Deprecations/PluginAnnotationContextDefinitionsRule.php, src/Rules/Deprecations/StaticServiceDeprecatedServiceRule.php, src/Rules/Drupal/RenderCallbackRule.php, src/Type/ContainerDynamicReturnTypeExtension.php, src/Type/DrupalClassResolverDynamicReturnTypeExtension.php, src/Type/DrupalServiceDynamicReturnTypeExtension.php, src/Type/EntityAccessControlHandlerReturnTypeExtension.php, src/Type/EntityQuery/ConfigEntityQueryType.php, src/Type/EntityQuery/ContentEntityQueryType.php, src/Type/EntityQuery/EntityQueryExecuteWithoutAccessCheckType.php, src/Type/EntityTypeManagerGetStorageDynamicReturnTypeExtension.php
=> Start using slevomat/coding-standard rules

phpstan.neon, stubs/Drupal/Core/Entity/ContentEntityInterface.stub, stubs/Drupal/Core/Entity/FieldableEntityInterface.stub, tests/src/Rules/EntityParameterTypehintRuleTest.php, tests/src/Rules/data/entity-parameters.php, tests/src/Type/EntityTypesTest.php, tests/src/Type/data/entity-type-stubs.php
Fixes #412 and provides iterable template for content entities.
=> Add stubs for ContentEntityInterface and FieldableEntityInterface

src/Rules/Drupal/LoadIncludes.php, src/Rules/Drupal/ModuleLoadInclude.php
=> do not use DIRECTORY_SEPARATOR in error messages

stubs/Drupal/Core/Entity/EntityInterface.stub
=> Add EntityInterface stub

stubs/Drupal/Core/Access/AccessResultInterface.stub, stubs/Drupal/Core/Entity/EntityTypeInterface.stub, stubs/Drupal/Core/Entity/FieldableEntityInterface.stub, stubs/Drupal/Core/Field/Plugin/Field/FieldDefinitionInterface.stub, stubs/Drupal/Core/Field/Plugin/Field/FieldItemListInterface.stub, stubs/Drupal/Core/Session/AccountInterface.stub, stubs/Twig/Environment.stub
=> Add missing stub dependency stubs

src/Drupal/ExtensionDiscovery.php
https://www.php.net/manual/en/splfileobject.fgets.php may return False
Ref #441
=> Fix preg_match() usage when looking for extension type

tests/src/Rules/RenderCallbackRuleTest.php, tests/src/Rules/data/bug-424.php
=> Test #lazy_builder and static::class concat for callback

rules.neon, src/Rules/Deprecations/SymfonyCmfRoutingInClassMethodSignatureRule.php, src/Rules/Drupal/DrupalRequestStackShimInClassMethodRule.php, src/Rules/Drupal/DrupalRequestStackShimInstantiationRule.php, tests/src/Rules/DrupalRequestStackShimInClassMethodRuleTest.php, tests/src/Rules/DrupalRequestStackShimInstantiationRuleTest.php, tests/src/Rules/data/request-stack.php
=> Forward compatibility shim added for Symfony 5 RequestStack rule

stubs/Drupal/Core/Entity/FieldableEntityInterface.stub
=> Specify T for FieldableEntityInterface stub

composer.json, src/Rules/Drupal/RenderCallbackRule.php
=> Replace deprecated PHPStan\Type\Constant\ConstantArrayType::findTypeAndMethodName() call

src/Rules/Drupal/EntityQuery/EntityQueryHasAccessCheckRule.php, tests/src/Rules/EntityQueryHasAccessCheckRuleTest.php
=> Update EntityQueryWithoutAccessRule rule message to use full Drupal message

src/Rules/Deprecations/AccessDeprecatedConstant.php
=> REQUEST_TIME pushed to 11.0.0 removal

src/Type/DrupalStaticEntityQueryDynamicReturnTypeExtension.php, src/Type/EntityQuery/EntityQueryDynamicReturnTypeExtension.php, tests/src/Rules/EntityQueryHasAccessCheckRuleTest.php, tests/src/Rules/data/bug-494.php
=> False negative accessCheck failure on entity queries with entity type coming from parameter 

src/Rules/Drupal/GlobalDrupalDependencyInjectionRule.php, tests/src/Rules/GlobalDrupalDependencyInjectionRuleTest.php, tests/src/Rules/data/bug-500.php
=> allow \Drupal static in enums

stubs/Drupal/Core/Field/FieldItemList.stub, tests/src/Type/EntityTypesTest.php, tests/src/Type/data/bug-499.php
=> stub FieldItemList::createItem return type

README.md
=> add links for discussion and Drupal slack channel

stubs/Drupal/Core/Field/FieldItemList.stub, stubs/Drupal/Core/TypedData/Plugin/DataType/ItemList.stub, tests/src/StubTest.php
=> Add stub validation test, fix stubs

src/Type/EntityQuery/AccessCheckTypeSpecifyingExtension.php, tests/src/Rules/AccessCheckImpossibleTypeCallRuleTest.php
=> Overwrite specified types for accessCheck type specifier

src/Rules/Drupal/EntityQuery/EntityQueryHasAccessCheckRule.php, tests/src/Rules/EntityQueryHasAccessCheckRuleTest.php, tests/src/Rules/data/bug-479.php
=> Ignore accessCheck on config entity queries

.github/workflows/php.yml, .github/workflows/phpstan-dev.yml
=>  Update to "actions/checkout@v3" and thus node.js 16

.gitignore
=> GitIgnore PHPStorm files

composer.json
=> Bump phpstan/phpstan to ^1.10.1

.github/workflows/php.yml, .github/workflows/phpstan-dev.yml, src/Rules/Drupal/RenderCallbackRule.php, tests/src/Rules/RenderCallbackRuleTest.php, tests/src/Rules/data/bug-527.php
=> Support TrustedCallback attribute for RenderCallbackRule

.github/workflows/php.yml, composer.json
=> allow drush/drush ^11 in require-dev

src/Type/DrupalStaticEntityQueryDynamicReturnTypeExtension.php, src/Type/EntityStorage/EntityStorageDynamicReturnTypeExtension.php, tests/src/Type/EntityQuery/EntityQueryDynamicReturnTypeExtensionTest.php, tests/src/Type/data/bug-522.php
=> use isSuperOf instead of instanceof checks for storage types

src/Type/EntityQuery/EntityQueryDynamicReturnTypeExtension.php, tests/src/Rules/EntityQueryHasAccessCheckRuleTest.php, tests/src/Rules/data/bug-545.php
=> EntityQueryDynamicReturnTypeExtension ignore count if unknown type

src/Rules/Drupal/LoadIncludeBase.php, tests/src/Rules/LoadIncludesRuleTest.php, tests/src/Rules/data/bug-547.php
=> Skip loadInclude if baseName is not resolveable

src/Rules/Drupal/LoadIncludes.php, tests/src/Rules/LoadIncludesRuleTest.php, tests/src/Rules/data/bug-177.php
=> Load includes not working from Drupal::moduleHandler()->loadInclude()

src/Rules/Drupal/RenderCallbackRule.php
=> Add date and date time render callbacks to RenderCallbackRule

.github/workflows/php.yml
=> Add Drupal core baseline check

.github/workflows/php.yml
=> Replace `set-output` commands

.github/workflows/php.yml, tests/src/Rules/ClassExtendsInternalClassRuleTest.php, tests/src/Rules/RequestStackGetMainRequestRuleTest.php, tests/src/Rules/SymfonyCmfRouteObjectInterfaceConstantsRuleTest.php, tests/src/Rules/SymfonyCmfRoutingInClassMethodSignatureRuleTest.php
=> Switch testing against 10.1.x-dev to 11.x-dev branch

src/Type/ContainerDynamicReturnTypeExtension.php, tests/src/Type/DrupalContainerDynamicReturnTypeTest.php, tests/src/Type/data/bug-563.php
=> ContainerDynamicReturnTypeExtension resolves constant string types

stubs/Drupal/Core/Entity/EntityStorageInterface.stub, stubs/Drupal/Core/Entity/RevisionableStorageInterface.stub
=> Support RevisionableStorageInterface and methods ::loadRevision() and ::deleteRevision() deprecation

src/Rules/Drupal/GlobalDrupalDependencyInjectionRule.php, src/Rules/Drupal/Tests/BrowserTestBaseDefaultThemeRule.php, tests/src/Rules/GlobalDrupalDependencyInjectionRuleTest.php, tests/src/Rules/data/bug-580.php
=> Better static scope checks for \Drupal static calls

src/Drupal/ServiceMap.php, tests/src/ServiceMapFactoryTest.php
=> Handle aliases before parent resolving in service map

rules.neon, src/Rules/Drupal/TestClassesProtectedPropertyModulesRule.php, tests/src/Rules/TestClassesProtectedPropertyModulesRuleTest.php, tests/src/Rules/data/test-cases-test-classes-protected-property-modules-rule.php
=> Detect public static $modules when it should be protected static $modules in tests

stubs/Drupal/KernelTests/KernelTestBase.stub
=> Stub $modules on KernelTestBase

README.md
=> Add information on why this package is needed

src/Drupal/DrupalServiceDefinition.php, src/Drupal/ServiceMap.php, tests/src/ServiceMapFactoryTest.php
=> Add decorator support to ServiceMap.

.circleci/config.yml, .github/workflows/php.yml, composer.json
=> PR Drop Drupal 8 from testing workflows

src/Drupal/ServiceMap.php, tests/src/ServiceMapFactoryTest.php
=> Do not error when a service decorates an unknown service.

.github/workflows/php.yml
=> PR Add PHP 8.2 to test workflow

.github/workflows/php.yml, tests/src/Rules/RevisionableStorageInterfaceStubTest.php
=> Deprecation fixed for loadRevison on RevisionableStorageInterface

stubs/Drupal/Core/Cache/CacheBackendInterface.stub, tests/src/Type/CacheBackendInterfaceStubTest.php, tests/src/Type/data/cache-backend-interface-stub.php
=> Define stub for cache object shape

.github/workflows/php.yml
=> Build integration missing 10.x

stubs/Drupal/Core/Lock/LockBackendInterface.stub, tests/src/Type/LockBackendInterfaceStubTest.php, tests/src/Type/data/lock-backend.php
=> Mark LockBackendInterface::acquire() as impure

.github/workflows/php.yml, src/Rules/Deprecations/SymfonyCmfRouteObjectInterfaceConstantsRule.php, src/Rules/Deprecations/SymfonyCmfRoutingInClassMethodSignatureRule.php, src/Rules/Drupal/RequestStackGetMainRequestRule.php
=> Add PHP 8.3 to workflow

extension.neon, src/Type/EntityRepositoryReturnTypeExtension.php, tests/src/Type/EntityRepositoryTypeTest.php, tests/src/Type/data/entity-repository.php
=> Add EntityRepositoryInterface return type extension

README.md, extension.neon, rules.neon
=> Support turning off @internal check

.github/workflows/php.yml, composer.json
=> Drop PHP 7.4

.github/workflows/php.yml, composer.json
=> Drop PHP 8.0

stubs/Drupal/Component/Render/MarkupInterface.stub, stubs/Drupal/text/Plugin/Field/FieldType/TextItem.stub, stubs/Drupal/text/Plugin/Field/FieldType/TextItemBase.stub, stubs/Drupal/text/Plugin/Field/FieldType/TextLongItem.stub, stubs/Drupal/text/Plugin/Field/FieldType/TextWithSummaryItem.stub, tests/src/Type/data/field-types.php
fixes https://github.com/mglaman/phpstan-drupal/issues/360
=> Add stubs for text field types

stubs/Drupal/datetime/Plugin/Field/FieldType/DateTimeItem.stub, stubs/Drupal/datetime/Plugin/Field/FieldType/DateTimeItemInterface.stub, tests/src/Type/data/field-types.php
Resolves https://github.com/mglaman/phpstan-drupal/issues/364
=> Add stubs for datetime field type

stubs/Drupal/comment/Plugin/Field/FieldType/CommentItem.stub, stubs/Drupal/comment/Plugin/Field/FieldType/CommentItemInterface.stub, tests/src/Type/data/field-types.php
Resolves https://github.com/mglaman/phpstan-drupal/issues/363
=> Add stubs for comment field type

README.md, composer.json, extension.neon, src/Drupal/DrupalAutoloader.php, tests/fixtures/config/phpunit-drupal-phpstan.neon, tests/src/Rules/AccessCheckImpossibleTypeCallRuleTest.php
Resolves https://github.com/mglaman/phpstan-drupal/pull/757
=> Upgrade to webflo/drupal-finder 1.3

src/Rules/Deprecations/SymfonyCmfRoutingInClassMethodSignatureRule.php, src/Type/ContainerDynamicReturnTypeExtension.php, src/Type/DrupalClassResolverDynamicReturnTypeExtension.php, src/Type/DrupalClassResolverReturnType.php, src/Type/DrupalServiceDynamicReturnTypeExtension.php, src/Type/DrupalStaticEntityQueryDynamicReturnTypeExtension.php, src/Type/EntityQuery/AccessCheckTypeSpecifyingExtension.php, src/Type/EntityQuery/EntityQueryAccessCheckDynamicReturnTypeExtension.php, src/Type/EntityQuery/EntityQueryDynamicReturnTypeExtension.php, src/Type/EntityRepositoryReturnTypeExtension.php, src/Type/EntityStorage/EntityStorageDynamicReturnTypeExtension.php, src/Type/EntityStorage/GetQueryReturnTypeExtension.php, src/Type/EntityTypeManagerGetStorageDynamicReturnTypeExtension.php
=> Removed deprecated ParametersAcceptorSelector::selectSingle()

src/Drupal/DrupalAutoloader.php
**Add support for shorthand service definition syntax (#817)**
=> Add support for shorthand service definition syntax

README.md
=> Fix 1.x branch support message

stubs/Drupal/Core/TypedData/Plugin/DataType/ItemList.stub
From https://github.com/mglaman/phpstan-drupal/pull/846#discussion_r2056530418
=> Stub ItemList::getIterator return type (2.x)

stubs/Drupal/Core/Field/EntityReferenceFieldItemList.stub, tests/src/Generics/EntityReferenceFieldItemListGenericTest.php, tests/src/Generics/data/bug-878.php
=> Overridden EntityReferenceFieldItemListInterface::referencedEntities generics error

stubs/Drupal/Core/Url.stub, tests/src/Type/data/url.php
#896 was causing test failures
=> Fix badly formatted doc for `Url::access` and add tests

stubs/Drupal/Core/Field/Plugin/Field/FieldType/TimestampItem.stub
=> TimestamItem value is int
